// DO NOT EDIT THIS: This file was generated by the Pyrin Golang Generator
package api


func (c *Client) AddItemToPlaylist(playlistId string, body AddItemToPlaylistBody, options Options) (*any, error) {
	path := Sprintf("/api/v1/playlists/%v/items", playlistId)
	url, err := createUrl(c.addr, path, options.Query)
	if err != nil {
		return nil, err
	}

	data := RequestData{
		Url: url,
		Method: "POST",
		ClientHeaders: c.Headers,
		Headers: options.Header,
	}
	return Request[any](data, body)
}


func (c *Client) AuthClaimQuickConnectCode(body AuthClaimQuickConnectCodeBody, options Options) (*any, error) {
	path := "/api/v1/auth/quick-connect/claim"
	url, err := createUrl(c.addr, path, options.Query)
	if err != nil {
		return nil, err
	}

	data := RequestData{
		Url: url,
		Method: "POST",
		ClientHeaders: c.Headers,
		Headers: options.Header,
	}
	return Request[any](data, body)
}

func (c *Client) AuthFinishProvider(body AuthFinishProviderBody, options Options) (*AuthFinishProvider, error) {
	path := "/api/v1/auth/providers/finish"
	url, err := createUrl(c.addr, path, options.Query)
	if err != nil {
		return nil, err
	}

	data := RequestData{
		Url: url,
		Method: "POST",
		ClientHeaders: c.Headers,
		Headers: options.Header,
	}
	return Request[AuthFinishProvider](data, body)
}

func (c *Client) AuthFinishQuickConnect(body AuthFinishQuickConnectBody, options Options) (*AuthFinishQuickConnect, error) {
	path := "/api/v1/auth/quick-connect/finish"
	url, err := createUrl(c.addr, path, options.Query)
	if err != nil {
		return nil, err
	}

	data := RequestData{
		Url: url,
		Method: "POST",
		ClientHeaders: c.Headers,
		Headers: options.Header,
	}
	return Request[AuthFinishQuickConnect](data, body)
}

func (c *Client) AuthGetProviderStatus(body AuthGetProviderStatusBody, options Options) (*AuthGetProviderStatus, error) {
	path := "/api/v1/auth/provider/status"
	url, err := createUrl(c.addr, path, options.Query)
	if err != nil {
		return nil, err
	}

	data := RequestData{
		Url: url,
		Method: "POST",
		ClientHeaders: c.Headers,
		Headers: options.Header,
	}
	return Request[AuthGetProviderStatus](data, body)
}

func (c *Client) AuthGetProviders(options Options) (*GetAuthProviders, error) {
	path := "/api/v1/auth/providers"
	url, err := createUrl(c.addr, path, options.Query)
	if err != nil {
		return nil, err
	}

	data := RequestData{
		Url: url,
		Method: "GET",
		ClientHeaders: c.Headers,
		Headers: options.Header,
	}
	return Request[GetAuthProviders](data, nil)
}

func (c *Client) AuthGetQuickConnectStatus(body AuthGetQuickConnectStatusBody, options Options) (*AuthGetQuickConnectStatus, error) {
	path := "/api/v1/auth/quick-connect/status"
	url, err := createUrl(c.addr, path, options.Query)
	if err != nil {
		return nil, err
	}

	data := RequestData{
		Url: url,
		Method: "POST",
		ClientHeaders: c.Headers,
		Headers: options.Header,
	}
	return Request[AuthGetQuickConnectStatus](data, body)
}

func (c *Client) AuthProviderInitiate(body AuthInitiateBody, options Options) (*AuthInitiate, error) {
	path := "/api/v1/auth/providers/initiate"
	url, err := createUrl(c.addr, path, options.Query)
	if err != nil {
		return nil, err
	}

	data := RequestData{
		Url: url,
		Method: "POST",
		ClientHeaders: c.Headers,
		Headers: options.Header,
	}
	return Request[AuthInitiate](data, body)
}

func (c *Client) AuthQuickConnectInitiate(options Options) (*AuthQuickConnectInitiate, error) {
	path := "/api/v1/auth/quick-connect/initiate"
	url, err := createUrl(c.addr, path, options.Query)
	if err != nil {
		return nil, err
	}

	data := RequestData{
		Url: url,
		Method: "POST",
		ClientHeaders: c.Headers,
		Headers: options.Header,
	}
	return Request[AuthQuickConnectInitiate](data, nil)
}

func (c *Client) CreateApiToken(body CreateApiTokenBody, options Options) (*CreateApiToken, error) {
	path := "/api/v1/me/apitokens"
	url, err := createUrl(c.addr, path, options.Query)
	if err != nil {
		return nil, err
	}

	data := RequestData{
		Url: url,
		Method: "POST",
		ClientHeaders: c.Headers,
		Headers: options.Header,
	}
	return Request[CreateApiToken](data, body)
}

func (c *Client) CreatePlaylist(body CreatePlaylistBody, options Options) (*CreatePlaylist, error) {
	path := "/api/v1/playlists"
	url, err := createUrl(c.addr, path, options.Query)
	if err != nil {
		return nil, err
	}

	data := RequestData{
		Url: url,
		Method: "POST",
		ClientHeaders: c.Headers,
		Headers: options.Header,
	}
	return Request[CreatePlaylist](data, body)
}

func (c *Client) CreateTrackFilter(body CreateTrackFilterBody, options Options) (*any, error) {
	path := "/api/v1/me/filters/tracks"
	url, err := createUrl(c.addr, path, options.Query)
	if err != nil {
		return nil, err
	}

	data := RequestData{
		Url: url,
		Method: "POST",
		ClientHeaders: c.Headers,
		Headers: options.Header,
	}
	return Request[any](data, body)
}

func (c *Client) DeleteApiToken(tokenId string, options Options) (*any, error) {
	path := Sprintf("/api/v1/me/apitokens/%v", tokenId)
	url, err := createUrl(c.addr, path, options.Query)
	if err != nil {
		return nil, err
	}

	data := RequestData{
		Url: url,
		Method: "DELETE",
		ClientHeaders: c.Headers,
		Headers: options.Header,
	}
	return Request[any](data, nil)
}

func (c *Client) DeletePlaylist(playlistId string, options Options) (*any, error) {
	path := Sprintf("/api/v1/playlists/%v", playlistId)
	url, err := createUrl(c.addr, path, options.Query)
	if err != nil {
		return nil, err
	}

	data := RequestData{
		Url: url,
		Method: "DELETE",
		ClientHeaders: c.Headers,
		Headers: options.Header,
	}
	return Request[any](data, nil)
}

func (c *Client) DeleteTrackFilter(filterId string, options Options) (*any, error) {
	path := Sprintf("/api/v1/me/filters/tracks/%v", filterId)
	url, err := createUrl(c.addr, path, options.Query)
	if err != nil {
		return nil, err
	}

	data := RequestData{
		Url: url,
		Method: "DELETE",
		ClientHeaders: c.Headers,
		Headers: options.Header,
	}
	return Request[any](data, nil)
}

func (c *Client) EditPlaylist(playlistId string, body EditPlaylistBody, options Options) (*any, error) {
	path := Sprintf("/api/v1/playlists/%v", playlistId)
	url, err := createUrl(c.addr, path, options.Query)
	if err != nil {
		return nil, err
	}

	data := RequestData{
		Url: url,
		Method: "PATCH",
		ClientHeaders: c.Headers,
		Headers: options.Header,
	}
	return Request[any](data, body)
}

func (c *Client) FavoriteTrack(trackId string, options Options) (*any, error) {
	path := Sprintf("/api/v1/me/favorites/tracks/%v", trackId)
	url, err := createUrl(c.addr, path, options.Query)
	if err != nil {
		return nil, err
	}

	data := RequestData{
		Url: url,
		Method: "POST",
		ClientHeaders: c.Headers,
		Headers: options.Header,
	}
	return Request[any](data, nil)
}

func (c *Client) GeneratePlaylistImage(playlistId string, options Options) (*any, error) {
	path := Sprintf("/api/v1/playlists/%v/images/generate", playlistId)
	url, err := createUrl(c.addr, path, options.Query)
	if err != nil {
		return nil, err
	}

	data := RequestData{
		Url: url,
		Method: "POST",
		ClientHeaders: c.Headers,
		Headers: options.Header,
	}
	return Request[any](data, nil)
}

func (c *Client) GetAlbumById(id string, options Options) (*GetAlbumById, error) {
	path := Sprintf("/api/v1/albums/%v", id)
	url, err := createUrl(c.addr, path, options.Query)
	if err != nil {
		return nil, err
	}

	data := RequestData{
		Url: url,
		Method: "GET",
		ClientHeaders: c.Headers,
		Headers: options.Header,
	}
	return Request[GetAlbumById](data, nil)
}


func (c *Client) GetAlbumTracks(id string, options Options) (*GetAlbumTracks, error) {
	path := Sprintf("/api/v1/albums/%v/tracks", id)
	url, err := createUrl(c.addr, path, options.Query)
	if err != nil {
		return nil, err
	}

	data := RequestData{
		Url: url,
		Method: "GET",
		ClientHeaders: c.Headers,
		Headers: options.Header,
	}
	return Request[GetAlbumTracks](data, nil)
}

func (c *Client) GetAlbums(options Options) (*GetAlbums, error) {
	path := "/api/v1/albums"
	url, err := createUrl(c.addr, path, options.Query)
	if err != nil {
		return nil, err
	}

	data := RequestData{
		Url: url,
		Method: "GET",
		ClientHeaders: c.Headers,
		Headers: options.Header,
	}
	return Request[GetAlbums](data, nil)
}

func (c *Client) GetApiTokens(options Options) (*GetApiTokens, error) {
	path := "/api/v1/me/apitokens"
	url, err := createUrl(c.addr, path, options.Query)
	if err != nil {
		return nil, err
	}

	data := RequestData{
		Url: url,
		Method: "GET",
		ClientHeaders: c.Headers,
		Headers: options.Header,
	}
	return Request[GetApiTokens](data, nil)
}

func (c *Client) GetArtistAlbums(id string, options Options) (*GetArtistAlbumsById, error) {
	path := Sprintf("/api/v1/artists/%v/albums", id)
	url, err := createUrl(c.addr, path, options.Query)
	if err != nil {
		return nil, err
	}

	data := RequestData{
		Url: url,
		Method: "GET",
		ClientHeaders: c.Headers,
		Headers: options.Header,
	}
	return Request[GetArtistAlbumsById](data, nil)
}

func (c *Client) GetArtistById(id string, options Options) (*GetArtistById, error) {
	path := Sprintf("/api/v1/artists/%v", id)
	url, err := createUrl(c.addr, path, options.Query)
	if err != nil {
		return nil, err
	}

	data := RequestData{
		Url: url,
		Method: "GET",
		ClientHeaders: c.Headers,
		Headers: options.Header,
	}
	return Request[GetArtistById](data, nil)
}


func (c *Client) GetArtists(options Options) (*GetArtists, error) {
	path := "/api/v1/artists"
	url, err := createUrl(c.addr, path, options.Query)
	if err != nil {
		return nil, err
	}

	data := RequestData{
		Url: url,
		Method: "GET",
		ClientHeaders: c.Headers,
		Headers: options.Header,
	}
	return Request[GetArtists](data, nil)
}

func (c *Client) GetFavoriteTrackIds(options Options) (*GetFavoriteTrackIds, error) {
	path := "/api/v1/me/favorites/tracks/ids"
	url, err := createUrl(c.addr, path, options.Query)
	if err != nil {
		return nil, err
	}

	data := RequestData{
		Url: url,
		Method: "GET",
		ClientHeaders: c.Headers,
		Headers: options.Header,
	}
	return Request[GetFavoriteTrackIds](data, nil)
}

func (c *Client) GetMe(options Options) (*GetMe, error) {
	path := "/api/v1/auth/me"
	url, err := createUrl(c.addr, path, options.Query)
	if err != nil {
		return nil, err
	}

	data := RequestData{
		Url: url,
		Method: "GET",
		ClientHeaders: c.Headers,
		Headers: options.Header,
	}
	return Request[GetMe](data, nil)
}

func (c *Client) GetMediaSettings(options Options) (*GetMediaSettings, error) {
	path := "/api/v1/media/settings"
	url, err := createUrl(c.addr, path, options.Query)
	if err != nil {
		return nil, err
	}

	data := RequestData{
		Url: url,
		Method: "GET",
		ClientHeaders: c.Headers,
		Headers: options.Header,
	}
	return Request[GetMediaSettings](data, nil)
}

func (c *Client) GetPlaylistById(playlistId string, options Options) (*GetPlaylistById, error) {
	path := Sprintf("/api/v1/playlists/%v", playlistId)
	url, err := createUrl(c.addr, path, options.Query)
	if err != nil {
		return nil, err
	}

	data := RequestData{
		Url: url,
		Method: "GET",
		ClientHeaders: c.Headers,
		Headers: options.Header,
	}
	return Request[GetPlaylistById](data, nil)
}


func (c *Client) GetPlaylistItemIds(playlistId string, options Options) (*GetPlaylistItemIds, error) {
	path := Sprintf("/api/v1/playlists/%v/ids", playlistId)
	url, err := createUrl(c.addr, path, options.Query)
	if err != nil {
		return nil, err
	}

	data := RequestData{
		Url: url,
		Method: "GET",
		ClientHeaders: c.Headers,
		Headers: options.Header,
	}
	return Request[GetPlaylistItemIds](data, nil)
}

func (c *Client) GetPlaylistItems(playlistId string, options Options) (*GetPlaylistItems, error) {
	path := Sprintf("/api/v1/playlists/%v/items", playlistId)
	url, err := createUrl(c.addr, path, options.Query)
	if err != nil {
		return nil, err
	}

	data := RequestData{
		Url: url,
		Method: "GET",
		ClientHeaders: c.Headers,
		Headers: options.Header,
	}
	return Request[GetPlaylistItems](data, nil)
}

func (c *Client) GetPlaylists(options Options) (*GetPlaylists, error) {
	path := "/api/v1/playlists"
	url, err := createUrl(c.addr, path, options.Query)
	if err != nil {
		return nil, err
	}

	data := RequestData{
		Url: url,
		Method: "GET",
		ClientHeaders: c.Headers,
		Headers: options.Header,
	}
	return Request[GetPlaylists](data, nil)
}

func (c *Client) GetQuickPlaylistIds(options Options) (*GetQuickPlaylistIds, error) {
	path := "/api/v1/me/quickplaylist"
	url, err := createUrl(c.addr, path, options.Query)
	if err != nil {
		return nil, err
	}

	data := RequestData{
		Url: url,
		Method: "GET",
		ClientHeaders: c.Headers,
		Headers: options.Header,
	}
	return Request[GetQuickPlaylistIds](data, nil)
}

func (c *Client) GetSystemInfo(options Options) (*GetSystemInfo, error) {
	path := "/api/v1/system/info"
	url, err := createUrl(c.addr, path, options.Query)
	if err != nil {
		return nil, err
	}

	data := RequestData{
		Url: url,
		Method: "GET",
		ClientHeaders: c.Headers,
		Headers: options.Header,
	}
	return Request[GetSystemInfo](data, nil)
}

func (c *Client) GetTrackById(id string, options Options) (*GetTrackById, error) {
	path := Sprintf("/api/v1/tracks/%v", id)
	url, err := createUrl(c.addr, path, options.Query)
	if err != nil {
		return nil, err
	}

	data := RequestData{
		Url: url,
		Method: "GET",
		ClientHeaders: c.Headers,
		Headers: options.Header,
	}
	return Request[GetTrackById](data, nil)
}

func (c *Client) GetTracks(options Options) (*GetTracks, error) {
	path := "/api/v1/tracks"
	url, err := createUrl(c.addr, path, options.Query)
	if err != nil {
		return nil, err
	}

	data := RequestData{
		Url: url,
		Method: "GET",
		ClientHeaders: c.Headers,
		Headers: options.Header,
	}
	return Request[GetTracks](data, nil)
}

func (c *Client) GetUser(userId string, options Options) (*GetUser, error) {
	path := Sprintf("/api/v1/users/%v", userId)
	url, err := createUrl(c.addr, path, options.Query)
	if err != nil {
		return nil, err
	}

	data := RequestData{
		Url: url,
		Method: "GET",
		ClientHeaders: c.Headers,
		Headers: options.Header,
	}
	return Request[GetUser](data, nil)
}


func (c *Client) GetUserTrackFavorites(userId string, options Options) (*GetUserFavorites, error) {
	path := Sprintf("/api/v1/users/%v/favorites/tracks", userId)
	url, err := createUrl(c.addr, path, options.Query)
	if err != nil {
		return nil, err
	}

	data := RequestData{
		Url: url,
		Method: "GET",
		ClientHeaders: c.Headers,
		Headers: options.Header,
	}
	return Request[GetUserFavorites](data, nil)
}

func (c *Client) GetUserTrackFilters(userId string, options Options) (*GetTrackFilters, error) {
	path := Sprintf("/api/v1/users/%v/filters/tracks", userId)
	url, err := createUrl(c.addr, path, options.Query)
	if err != nil {
		return nil, err
	}

	data := RequestData{
		Url: url,
		Method: "GET",
		ClientHeaders: c.Headers,
		Headers: options.Header,
	}
	return Request[GetTrackFilters](data, nil)
}

func (c *Client) RemovePlaylistItem(playlistId string, body RemovePlaylistItemBody, options Options) (*any, error) {
	path := Sprintf("/api/v1/playlists/%v/items", playlistId)
	url, err := createUrl(c.addr, path, options.Query)
	if err != nil {
		return nil, err
	}

	data := RequestData{
		Url: url,
		Method: "DELETE",
		ClientHeaders: c.Headers,
		Headers: options.Header,
	}
	return Request[any](data, body)
}

func (c *Client) ReorderPlaylistItems(playlistId string, body ReorderPlaylistItemsBody, options Options) (*any, error) {
	path := Sprintf("/api/v1/playlists/%v/items/reorder", playlistId)
	url, err := createUrl(c.addr, path, options.Query)
	if err != nil {
		return nil, err
	}

	data := RequestData{
		Url: url,
		Method: "POST",
		ClientHeaders: c.Headers,
		Headers: options.Header,
	}
	return Request[any](data, body)
}

func (c *Client) RunTask(taskName string, options Options) (*any, error) {
	path := Sprintf("/api/v1/system/task/%v", taskName)
	url, err := createUrl(c.addr, path, options.Query)
	if err != nil {
		return nil, err
	}

	data := RequestData{
		Url: url,
		Method: "POST",
		ClientHeaders: c.Headers,
		Headers: options.Header,
	}
	return Request[any](data, nil)
}

func (c *Client) SearchAlbums(options Options) (*SearchAlbums, error) {
	path := "/api/v1/search/albums"
	url, err := createUrl(c.addr, path, options.Query)
	if err != nil {
		return nil, err
	}

	data := RequestData{
		Url: url,
		Method: "GET",
		ClientHeaders: c.Headers,
		Headers: options.Header,
	}
	return Request[SearchAlbums](data, nil)
}

func (c *Client) SearchArtists(options Options) (*SearchArtists, error) {
	path := "/api/v1/search/artists"
	url, err := createUrl(c.addr, path, options.Query)
	if err != nil {
		return nil, err
	}

	data := RequestData{
		Url: url,
		Method: "GET",
		ClientHeaders: c.Headers,
		Headers: options.Header,
	}
	return Request[SearchArtists](data, nil)
}

func (c *Client) SearchPlaylists(options Options) (*SearchPlaylists, error) {
	path := "/api/v1/search/playlists"
	url, err := createUrl(c.addr, path, options.Query)
	if err != nil {
		return nil, err
	}

	data := RequestData{
		Url: url,
		Method: "GET",
		ClientHeaders: c.Headers,
		Headers: options.Header,
	}
	return Request[SearchPlaylists](data, nil)
}

func (c *Client) SearchTracks(options Options) (*SearchTracks, error) {
	path := "/api/v1/search/tracks"
	url, err := createUrl(c.addr, path, options.Query)
	if err != nil {
		return nil, err
	}

	data := RequestData{
		Url: url,
		Method: "GET",
		ClientHeaders: c.Headers,
		Headers: options.Header,
	}
	return Request[SearchTracks](data, nil)
}

func (c *Client) SearchUsers(options Options) (*SearchUsers, error) {
	path := "/api/v1/search/users"
	url, err := createUrl(c.addr, path, options.Query)
	if err != nil {
		return nil, err
	}

	data := RequestData{
		Url: url,
		Method: "GET",
		ClientHeaders: c.Headers,
		Headers: options.Header,
	}
	return Request[SearchUsers](data, nil)
}

func (c *Client) SetQuickPlaylist(body SetQuickPlaylistBody, options Options) (*any, error) {
	path := "/api/v1/me/quickplaylist"
	url, err := createUrl(c.addr, path, options.Query)
	if err != nil {
		return nil, err
	}

	data := RequestData{
		Url: url,
		Method: "POST",
		ClientHeaders: c.Headers,
		Headers: options.Header,
	}
	return Request[any](data, body)
}



func (c *Client) UnfavoriteTrack(trackId string, options Options) (*any, error) {
	path := Sprintf("/api/v1/me/favorites/tracks/%v", trackId)
	url, err := createUrl(c.addr, path, options.Query)
	if err != nil {
		return nil, err
	}

	data := RequestData{
		Url: url,
		Method: "DELETE",
		ClientHeaders: c.Headers,
		Headers: options.Header,
	}
	return Request[any](data, nil)
}

func (c *Client) UpdateMe(body UpdateMeBody, options Options) (*any, error) {
	path := "/api/v1/me"
	url, err := createUrl(c.addr, path, options.Query)
	if err != nil {
		return nil, err
	}

	data := RequestData{
		Url: url,
		Method: "PATCH",
		ClientHeaders: c.Headers,
		Headers: options.Header,
	}
	return Request[any](data, body)
}

func (c *Client) UpdateTrackFilter(filterId string, body UpdateTrackFilterBody, options Options) (*any, error) {
	path := Sprintf("/api/v1/me/filters/tracks/%v", filterId)
	url, err := createUrl(c.addr, path, options.Query)
	if err != nil {
		return nil, err
	}

	data := RequestData{
		Url: url,
		Method: "PATCH",
		ClientHeaders: c.Headers,
		Headers: options.Header,
	}
	return Request[any](data, body)
}

func (c *Client) UploadPlaylistImage(playlistId string, boundary string, body Reader, options Options) (*any, error) {
	path := Sprintf("/api/v1/playlists/%v/image/upload", playlistId)
	url, err := createUrl(c.addr, path, options.Query)
	if err != nil {
		return nil, err
	}

	data := RequestData{
		Url: url,
		Method: "POST",
		ClientHeaders: c.Headers,
		Headers: options.Header,
	}
	return RequestForm[any](data, boundary, body)
}

func (c *ClientUrls) AddItemToPlaylist(playlistId string) (*URL, error) {
	path := Sprintf("/api/v1/playlists/%v/items", playlistId)
	return c.getUrl(path)
}

func (c *ClientUrls) AuthCallback() (*URL, error) {
	path := "/api/v1/auth/providers/callback"
	return c.getUrl(path)
}

func (c *ClientUrls) AuthClaimQuickConnectCode() (*URL, error) {
	path := "/api/v1/auth/quick-connect/claim"
	return c.getUrl(path)
}

func (c *ClientUrls) AuthFinishProvider() (*URL, error) {
	path := "/api/v1/auth/providers/finish"
	return c.getUrl(path)
}

func (c *ClientUrls) AuthFinishQuickConnect() (*URL, error) {
	path := "/api/v1/auth/quick-connect/finish"
	return c.getUrl(path)
}

func (c *ClientUrls) AuthGetProviderStatus() (*URL, error) {
	path := "/api/v1/auth/provider/status"
	return c.getUrl(path)
}

func (c *ClientUrls) AuthGetProviders() (*URL, error) {
	path := "/api/v1/auth/providers"
	return c.getUrl(path)
}

func (c *ClientUrls) AuthGetQuickConnectStatus() (*URL, error) {
	path := "/api/v1/auth/quick-connect/status"
	return c.getUrl(path)
}

func (c *ClientUrls) AuthProviderInitiate() (*URL, error) {
	path := "/api/v1/auth/providers/initiate"
	return c.getUrl(path)
}

func (c *ClientUrls) AuthQuickConnectInitiate() (*URL, error) {
	path := "/api/v1/auth/quick-connect/initiate"
	return c.getUrl(path)
}

func (c *ClientUrls) CreateApiToken() (*URL, error) {
	path := "/api/v1/me/apitokens"
	return c.getUrl(path)
}

func (c *ClientUrls) CreatePlaylist() (*URL, error) {
	path := "/api/v1/playlists"
	return c.getUrl(path)
}

func (c *ClientUrls) CreateTrackFilter() (*URL, error) {
	path := "/api/v1/me/filters/tracks"
	return c.getUrl(path)
}

func (c *ClientUrls) DeleteApiToken(tokenId string) (*URL, error) {
	path := Sprintf("/api/v1/me/apitokens/%v", tokenId)
	return c.getUrl(path)
}

func (c *ClientUrls) DeletePlaylist(playlistId string) (*URL, error) {
	path := Sprintf("/api/v1/playlists/%v", playlistId)
	return c.getUrl(path)
}

func (c *ClientUrls) DeleteTrackFilter(filterId string) (*URL, error) {
	path := Sprintf("/api/v1/me/filters/tracks/%v", filterId)
	return c.getUrl(path)
}

func (c *ClientUrls) EditPlaylist(playlistId string) (*URL, error) {
	path := Sprintf("/api/v1/playlists/%v", playlistId)
	return c.getUrl(path)
}

func (c *ClientUrls) FavoriteTrack(trackId string) (*URL, error) {
	path := Sprintf("/api/v1/me/favorites/tracks/%v", trackId)
	return c.getUrl(path)
}

func (c *ClientUrls) GeneratePlaylistImage(playlistId string) (*URL, error) {
	path := Sprintf("/api/v1/playlists/%v/images/generate", playlistId)
	return c.getUrl(path)
}

func (c *ClientUrls) GetAlbumById(id string) (*URL, error) {
	path := Sprintf("/api/v1/albums/%v", id)
	return c.getUrl(path)
}

func (c *ClientUrls) GetAlbumImage(albumId string, image string) (*URL, error) {
	path := Sprintf("/files/albums/images/%v/%v", albumId, image)
	return c.getUrl(path)
}

func (c *ClientUrls) GetAlbumTracks(id string) (*URL, error) {
	path := Sprintf("/api/v1/albums/%v/tracks", id)
	return c.getUrl(path)
}

func (c *ClientUrls) GetAlbums() (*URL, error) {
	path := "/api/v1/albums"
	return c.getUrl(path)
}

func (c *ClientUrls) GetApiTokens() (*URL, error) {
	path := "/api/v1/me/apitokens"
	return c.getUrl(path)
}

func (c *ClientUrls) GetArtistAlbums(id string) (*URL, error) {
	path := Sprintf("/api/v1/artists/%v/albums", id)
	return c.getUrl(path)
}

func (c *ClientUrls) GetArtistById(id string) (*URL, error) {
	path := Sprintf("/api/v1/artists/%v", id)
	return c.getUrl(path)
}

func (c *ClientUrls) GetArtistImage(artistId string, image string) (*URL, error) {
	path := Sprintf("/files/artists/images/%v/%v", artistId, image)
	return c.getUrl(path)
}

func (c *ClientUrls) GetArtists() (*URL, error) {
	path := "/api/v1/artists"
	return c.getUrl(path)
}

func (c *ClientUrls) GetFavoriteTrackIds() (*URL, error) {
	path := "/api/v1/me/favorites/tracks/ids"
	return c.getUrl(path)
}

func (c *ClientUrls) GetMe() (*URL, error) {
	path := "/api/v1/auth/me"
	return c.getUrl(path)
}

func (c *ClientUrls) GetMediaSettings() (*URL, error) {
	path := "/api/v1/media/settings"
	return c.getUrl(path)
}

func (c *ClientUrls) GetPlaylistById(playlistId string) (*URL, error) {
	path := Sprintf("/api/v1/playlists/%v", playlistId)
	return c.getUrl(path)
}

func (c *ClientUrls) GetPlaylistImage(playlistId string, image string) (*URL, error) {
	path := Sprintf("/files/playlists/images/%v/%v", playlistId, image)
	return c.getUrl(path)
}

func (c *ClientUrls) GetPlaylistItemIds(playlistId string) (*URL, error) {
	path := Sprintf("/api/v1/playlists/%v/ids", playlistId)
	return c.getUrl(path)
}

func (c *ClientUrls) GetPlaylistItems(playlistId string) (*URL, error) {
	path := Sprintf("/api/v1/playlists/%v/items", playlistId)
	return c.getUrl(path)
}

func (c *ClientUrls) GetPlaylists() (*URL, error) {
	path := "/api/v1/playlists"
	return c.getUrl(path)
}

func (c *ClientUrls) GetQuickPlaylistIds() (*URL, error) {
	path := "/api/v1/me/quickplaylist"
	return c.getUrl(path)
}

func (c *ClientUrls) GetSystemInfo() (*URL, error) {
	path := "/api/v1/system/info"
	return c.getUrl(path)
}

func (c *ClientUrls) GetTrackById(id string) (*URL, error) {
	path := Sprintf("/api/v1/tracks/%v", id)
	return c.getUrl(path)
}

func (c *ClientUrls) GetTracks() (*URL, error) {
	path := "/api/v1/tracks"
	return c.getUrl(path)
}

func (c *ClientUrls) GetUser(userId string) (*URL, error) {
	path := Sprintf("/api/v1/users/%v", userId)
	return c.getUrl(path)
}

func (c *ClientUrls) GetUserImage(userId string, image string) (*URL, error) {
	path := Sprintf("/files/users/images/%v/%v", userId, image)
	return c.getUrl(path)
}

func (c *ClientUrls) GetUserTrackFavorites(userId string) (*URL, error) {
	path := Sprintf("/api/v1/users/%v/favorites/tracks", userId)
	return c.getUrl(path)
}

func (c *ClientUrls) GetUserTrackFilters(userId string) (*URL, error) {
	path := Sprintf("/api/v1/users/%v/filters/tracks", userId)
	return c.getUrl(path)
}

func (c *ClientUrls) RemovePlaylistItem(playlistId string) (*URL, error) {
	path := Sprintf("/api/v1/playlists/%v/items", playlistId)
	return c.getUrl(path)
}

func (c *ClientUrls) ReorderPlaylistItems(playlistId string) (*URL, error) {
	path := Sprintf("/api/v1/playlists/%v/items/reorder", playlistId)
	return c.getUrl(path)
}

func (c *ClientUrls) RunTask(taskName string) (*URL, error) {
	path := Sprintf("/api/v1/system/task/%v", taskName)
	return c.getUrl(path)
}

func (c *ClientUrls) SearchAlbums() (*URL, error) {
	path := "/api/v1/search/albums"
	return c.getUrl(path)
}

func (c *ClientUrls) SearchArtists() (*URL, error) {
	path := "/api/v1/search/artists"
	return c.getUrl(path)
}

func (c *ClientUrls) SearchPlaylists() (*URL, error) {
	path := "/api/v1/search/playlists"
	return c.getUrl(path)
}

func (c *ClientUrls) SearchTracks() (*URL, error) {
	path := "/api/v1/search/tracks"
	return c.getUrl(path)
}

func (c *ClientUrls) SearchUsers() (*URL, error) {
	path := "/api/v1/search/users"
	return c.getUrl(path)
}

func (c *ClientUrls) SetQuickPlaylist() (*URL, error) {
	path := "/api/v1/me/quickplaylist"
	return c.getUrl(path)
}

func (c *ClientUrls) SseHandler() (*URL, error) {
	path := "/api/v1/system/sse"
	return c.getUrl(path)
}

func (c *ClientUrls) StreamTrack(trackId string) (*URL, error) {
	path := Sprintf("/api/v1/media/stream/tracks/%v", trackId)
	return c.getUrl(path)
}

func (c *ClientUrls) UnfavoriteTrack(trackId string) (*URL, error) {
	path := Sprintf("/api/v1/me/favorites/tracks/%v", trackId)
	return c.getUrl(path)
}

func (c *ClientUrls) UpdateMe() (*URL, error) {
	path := "/api/v1/me"
	return c.getUrl(path)
}

func (c *ClientUrls) UpdateTrackFilter(filterId string) (*URL, error) {
	path := Sprintf("/api/v1/me/filters/tracks/%v", filterId)
	return c.getUrl(path)
}

func (c *ClientUrls) UploadPlaylistImage(playlistId string) (*URL, error) {
	path := Sprintf("/api/v1/playlists/%v/image/upload", playlistId)
	return c.getUrl(path)
}
