// DO NOT EDIT THIS: This file was generated by the Pyrin Golang Generator
package api

// Name: AddItemToPlaylistBody
type AddItemToPlaylistBody struct {
	// Name: AddItemToPlaylistBody.trackId
	TrackId string `json:"trackId"`
}

// Name: Images
type Images struct {
	// Name: Images.original
	Original string `json:"original"`
	// Name: Images.small
	Small string `json:"small"`
	// Name: Images.medium
	Medium string `json:"medium"`
	// Name: Images.large
	Large string `json:"large"`
}

// Name: ArtistInfo
type ArtistInfo struct {
	// Name: ArtistInfo.id
	Id string `json:"id"`
	// Name: ArtistInfo.name
	Name string `json:"name"`
}

// Name: Album
type Album struct {
	// Name: Album.id
	Id string `json:"id"`
	// Name: Album.name
	Name string `json:"name"`
	// Name: Album.year
	Year *int `json:"year,omitempty"`
	// Name: Album.coverArt
	CoverArt Images `json:"coverArt"`
	// Name: Album.artists
	Artists []ArtistInfo `json:"artists"`
	// Name: Album.tags
	Tags []string `json:"tags"`
	// Name: Album.created
	Created string `json:"created"`
	// Name: Album.updated
	Updated string `json:"updated"`
}

// Name: ApiToken
type ApiToken struct {
	// Name: ApiToken.id
	Id string `json:"id"`
	// Name: ApiToken.name
	Name string `json:"name"`
	// Name: ApiToken.created
	Created string `json:"created"`
	// Name: ApiToken.updated
	Updated string `json:"updated"`
}

// Name: Artist
type Artist struct {
	// Name: Artist.id
	Id string `json:"id"`
	// Name: Artist.name
	Name string `json:"name"`
	// Name: Artist.coverArt
	CoverArt Images `json:"coverArt"`
	// Name: Artist.tags
	Tags []string `json:"tags"`
	// Name: Artist.created
	Created string `json:"created"`
	// Name: Artist.updated
	Updated string `json:"updated"`
}

// Name: AuthClaimQuickConnectCodeBody
type AuthClaimQuickConnectCodeBody struct {
	// Name: AuthClaimQuickConnectCodeBody.code
	Code string `json:"code"`
}

// Name: AuthFinishProvider
type AuthFinishProvider struct {
	// Name: AuthFinishProvider.token
	Token string `json:"token"`
}

// Name: AuthFinishProviderBody
type AuthFinishProviderBody struct {
	// Name: AuthFinishProviderBody.requestId
	RequestId string `json:"requestId"`
	// Name: AuthFinishProviderBody.challenge
	Challenge string `json:"challenge"`
}

// Name: AuthFinishQuickConnect
type AuthFinishQuickConnect struct {
	// Name: AuthFinishQuickConnect.token
	Token string `json:"token"`
}

// Name: AuthFinishQuickConnectBody
type AuthFinishQuickConnectBody struct {
	// Name: AuthFinishQuickConnectBody.code
	Code string `json:"code"`
	// Name: AuthFinishQuickConnectBody.challenge
	Challenge string `json:"challenge"`
}

// Name: AuthGetProviderStatus
type AuthGetProviderStatus struct {
	// Name: AuthGetProviderStatus.status
	Status string `json:"status"`
}

// Name: AuthGetProviderStatusBody
type AuthGetProviderStatusBody struct {
	// Name: AuthGetProviderStatusBody.requestId
	RequestId string `json:"requestId"`
	// Name: AuthGetProviderStatusBody.challenge
	Challenge string `json:"challenge"`
}

// Name: AuthGetQuickConnectStatus
type AuthGetQuickConnectStatus struct {
	// Name: AuthGetQuickConnectStatus.status
	Status string `json:"status"`
}

// Name: AuthGetQuickConnectStatusBody
type AuthGetQuickConnectStatusBody struct {
	// Name: AuthGetQuickConnectStatusBody.code
	Code string `json:"code"`
	// Name: AuthGetQuickConnectStatusBody.challenge
	Challenge string `json:"challenge"`
}

// Name: AuthInitiate
type AuthInitiate struct {
	// Name: AuthInitiate.requestId
	RequestId string `json:"requestId"`
	// Name: AuthInitiate.authUrl
	AuthUrl string `json:"authUrl"`
	// Name: AuthInitiate.challenge
	Challenge string `json:"challenge"`
	// Name: AuthInitiate.expiresAt
	ExpiresAt string `json:"expiresAt"`
}

// Name: AuthInitiateBody
type AuthInitiateBody struct {
	// Name: AuthInitiateBody.providerId
	ProviderId string `json:"providerId"`
}

// Name: AuthProvider
type AuthProvider struct {
	// Name: AuthProvider.id
	Id string `json:"id"`
	// Name: AuthProvider.displayName
	DisplayName string `json:"displayName"`
}

// Name: AuthQuickConnectInitiate
type AuthQuickConnectInitiate struct {
	// Name: AuthQuickConnectInitiate.code
	Code string `json:"code"`
	// Name: AuthQuickConnectInitiate.challenge
	Challenge string `json:"challenge"`
	// Name: AuthQuickConnectInitiate.authUrl
	AuthUrl string `json:"authUrl"`
	// Name: AuthQuickConnectInitiate.expiresAt
	ExpiresAt string `json:"expiresAt"`
}

// Name: CreateApiToken
type CreateApiToken struct {
	// Name: CreateApiToken.token
	Token string `json:"token"`
}

// Name: CreateApiTokenBody
type CreateApiTokenBody struct {
	// Name: CreateApiTokenBody.name
	Name string `json:"name"`
}

// Name: CreatePlaylist
type CreatePlaylist struct {
	// Name: CreatePlaylist.id
	Id string `json:"id"`
}

// Name: CreatePlaylistBody
type CreatePlaylistBody struct {
	// Name: CreatePlaylistBody.name
	Name string `json:"name"`
}

// Name: CreateTrackFilterBody
type CreateTrackFilterBody struct {
	// Name: CreateTrackFilterBody.name
	Name string `json:"name"`
	// Name: CreateTrackFilterBody.filter
	Filter string `json:"filter"`
}

// Name: EditPlaylistBody
type EditPlaylistBody struct {
	// Name: EditPlaylistBody.name
	Name *string `json:"name,omitempty"`
	// Name: EditPlaylistBody.coverUrl
	CoverUrl *string `json:"coverUrl,omitempty"`
}

// Name: GetAlbumById
type GetAlbumById struct {
	// Name: GetAlbumById.album
	Album Album `json:"album"`
}

// Name: Track
type Track struct {
	// Name: Track.id
	Id string `json:"id"`
	// Name: Track.name
	Name string `json:"name"`
	// Name: Track.order
	Order *int `json:"order,omitempty"`
	// Name: Track.duration
	Duration int `json:"duration"`
	// Name: Track.number
	Number *int `json:"number,omitempty"`
	// Name: Track.year
	Year *int `json:"year,omitempty"`
	// Name: Track.coverArt
	CoverArt Images `json:"coverArt"`
	// Name: Track.albumId
	AlbumId string `json:"albumId"`
	// Name: Track.albumName
	AlbumName string `json:"albumName"`
	// Name: Track.artists
	Artists []ArtistInfo `json:"artists"`
	// Name: Track.tags
	Tags []string `json:"tags"`
	// Name: Track.created
	Created string `json:"created"`
	// Name: Track.updated
	Updated string `json:"updated"`
}

// Name: GetAlbumTracks
type GetAlbumTracks struct {
	// Name: GetAlbumTracks.tracks
	Tracks []Track `json:"tracks"`
}

// Name: Page
type Page struct {
	// Name: Page.page
	Page int `json:"page"`
	// Name: Page.perPage
	PerPage int `json:"perPage"`
	// Name: Page.totalItems
	TotalItems int `json:"totalItems"`
	// Name: Page.totalPages
	TotalPages int `json:"totalPages"`
}

// Name: GetAlbums
type GetAlbums struct {
	// Name: GetAlbums.page
	Page Page `json:"page"`
	// Name: GetAlbums.albums
	Albums []Album `json:"albums"`
}

// Name: GetApiTokens
type GetApiTokens struct {
	// Name: GetApiTokens.tokens
	Tokens []ApiToken `json:"tokens"`
}

// Name: GetArtistAlbumsById
type GetArtistAlbumsById struct {
	// Name: GetArtistAlbumsById.albums
	Albums []Album `json:"albums"`
}

// Name: GetArtistById
type GetArtistById struct {
	// Name: GetArtistById.artist
	Artist Artist `json:"artist"`
}

// Name: GetArtists
type GetArtists struct {
	// Name: GetArtists.page
	Page Page `json:"page"`
	// Name: GetArtists.artists
	Artists []Artist `json:"artists"`
}

// Name: GetAuthProviders
type GetAuthProviders struct {
	// Name: GetAuthProviders.providers
	Providers []AuthProvider `json:"providers"`
}

// Name: GetFavoriteTrackIds
type GetFavoriteTrackIds struct {
	// Name: GetFavoriteTrackIds.ids
	Ids []string `json:"ids"`
}

// Name: GetMe
type GetMe struct {
	// Name: GetMe.id
	Id string `json:"id"`
	// Name: GetMe.email
	Email string `json:"email"`
	// Name: GetMe.displayName
	DisplayName string `json:"displayName"`
	// Name: GetMe.role
	Role string `json:"role"`
	// Name: GetMe.picture
	Picture Images `json:"picture"`
	// Name: GetMe.quickPlaylist
	QuickPlaylist *string `json:"quickPlaylist,omitempty"`
}

// Name: MediaFormat
type MediaFormat struct {
	// Name: MediaFormat.name
	Name string `json:"name"`
	// Name: MediaFormat.format
	Format string `json:"format"`
	// Name: MediaFormat.ext
	Ext string `json:"ext"`
	// Name: MediaFormat.qualityHighBitrate
	QualityHighBitrate int `json:"qualityHighBitrate"`
	// Name: MediaFormat.qualityMediumBitrate
	QualityMediumBitrate int `json:"qualityMediumBitrate"`
	// Name: MediaFormat.qualityLowBitrate
	QualityLowBitrate int `json:"qualityLowBitrate"`
	// Name: MediaFormat.order
	Order int `json:"order"`
}

// Name: MediaDeviceSpec
type MediaDeviceSpec struct {
	// Name: MediaDeviceSpec.name
	Name string `json:"name"`
	// Name: MediaDeviceSpec.preferedFormat
	PreferedFormat string `json:"preferedFormat"`
	// Name: MediaDeviceSpec.allowedFormats
	AllowedFormats []string `json:"allowedFormats"`
}

// Name: GetMediaSettings
type GetMediaSettings struct {
	// Name: GetMediaSettings.formats
	Formats []MediaFormat `json:"formats"`
	// Name: GetMediaSettings.deviceSpecs
	DeviceSpecs []MediaDeviceSpec `json:"deviceSpecs"`
}

// Name: Playlist
type Playlist struct {
	// Name: Playlist.id
	Id string `json:"id"`
	// Name: Playlist.name
	Name string `json:"name"`
	// Name: Playlist.coverArt
	CoverArt Images `json:"coverArt"`
	// Name: Playlist.ownerId
	OwnerId string `json:"ownerId"`
	// Name: Playlist.ownerDisplayName
	OwnerDisplayName string `json:"ownerDisplayName"`
	// Name: Playlist.ownerPicture
	OwnerPicture Images `json:"ownerPicture"`
	// Name: Playlist.trackCount
	TrackCount int `json:"trackCount"`
	// Name: Playlist.created
	Created string `json:"created"`
	// Name: Playlist.updated
	Updated string `json:"updated"`
}

// Name: GetPlaylistById
type GetPlaylistById struct {
	// Name: GetPlaylistById.playlist
	Playlist Playlist `json:"playlist"`
}

// Name: GetPlaylistItemIds
type GetPlaylistItemIds struct {
	// Name: GetPlaylistItemIds.ids
	Ids []string `json:"ids"`
}

// Name: GetPlaylistItems
type GetPlaylistItems struct {
	// Name: GetPlaylistItems.page
	Page Page `json:"page"`
	// Name: GetPlaylistItems.items
	Items []Track `json:"items"`
}

// Name: GetPlaylists
type GetPlaylists struct {
	// Name: GetPlaylists.page
	Page Page `json:"page"`
	// Name: GetPlaylists.playlists
	Playlists []Playlist `json:"playlists"`
}

// Name: GetQuickPlaylistIds
type GetQuickPlaylistIds struct {
	// Name: GetQuickPlaylistIds.ids
	Ids []string `json:"ids"`
}

// Name: GetSystemInfo
type GetSystemInfo struct {
	// Name: GetSystemInfo.version
	Version string `json:"version"`
}

// Name: GetTrackById
type GetTrackById struct {
	// Name: GetTrackById.track
	Track Track `json:"track"`
}

// Name: TrackFilter
type TrackFilter struct {
	// Name: TrackFilter.filterId
	FilterId string `json:"filterId"`
	// Name: TrackFilter.userId
	UserId string `json:"userId"`
	// Name: TrackFilter.name
	Name string `json:"name"`
	// Name: TrackFilter.filter
	Filter string `json:"filter"`
	// Name: TrackFilter.created
	Created string `json:"created"`
	// Name: TrackFilter.updated
	Updated string `json:"updated"`
}

// Name: GetTrackFilters
type GetTrackFilters struct {
	// Name: GetTrackFilters.filters
	Filters []TrackFilter `json:"filters"`
}

// Name: GetTracks
type GetTracks struct {
	// Name: GetTracks.page
	Page Page `json:"page"`
	// Name: GetTracks.tracks
	Tracks []Track `json:"tracks"`
}

// Name: UserData
type UserData struct {
	// Name: UserData.id
	Id string `json:"id"`
	// Name: UserData.displayName
	DisplayName string `json:"displayName"`
	// Name: UserData.role
	Role string `json:"role"`
	// Name: UserData.picture
	Picture Images `json:"picture"`
	// Name: UserData.created
	Created string `json:"created"`
}

// Name: GetUser
type GetUser struct {
	// Name: GetUser.user
	User UserData `json:"user"`
}

// Name: GetUserFavorites
type GetUserFavorites struct {
	// Name: GetUserFavorites.page
	Page Page `json:"page"`
	// Name: GetUserFavorites.items
	Items []Track `json:"items"`
}

// Name: RemovePlaylistItemBody
type RemovePlaylistItemBody struct {
	// Name: RemovePlaylistItemBody.trackId
	TrackId string `json:"trackId"`
}

// Name: ReorderPlaylistItemsBody
type ReorderPlaylistItemsBody struct {
	// Name: ReorderPlaylistItemsBody.before
	Before bool `json:"before"`
	// Name: ReorderPlaylistItemsBody.anchorTrackId
	AnchorTrackId string `json:"anchorTrackId"`
	// Name: ReorderPlaylistItemsBody.trackIds
	TrackIds []string `json:"trackIds"`
}

// Name: SearchAlbums
type SearchAlbums struct {
	// Name: SearchAlbums.page
	Page Page `json:"page"`
	// Name: SearchAlbums.albums
	Albums []Album `json:"albums"`
}

// Name: SearchArtists
type SearchArtists struct {
	// Name: SearchArtists.page
	Page Page `json:"page"`
	// Name: SearchArtists.artists
	Artists []Artist `json:"artists"`
}

// Name: SearchPlaylists
type SearchPlaylists struct {
	// Name: SearchPlaylists.page
	Page Page `json:"page"`
	// Name: SearchPlaylists.playlists
	Playlists []Playlist `json:"playlists"`
}

// Name: SearchTracks
type SearchTracks struct {
	// Name: SearchTracks.page
	Page Page `json:"page"`
	// Name: SearchTracks.tracks
	Tracks []Track `json:"tracks"`
}

// Name: SearchUsers
type SearchUsers struct {
	// Name: SearchUsers.page
	Page Page `json:"page"`
	// Name: SearchUsers.users
	Users []UserData `json:"users"`
}

// Name: SetQuickPlaylistBody
type SetQuickPlaylistBody struct {
	// Name: SetQuickPlaylistBody.playlistId
	PlaylistId string `json:"playlistId"`
}

// Name: UpdateMeBody
type UpdateMeBody struct {
	// Name: UpdateMeBody.displayName
	DisplayName *string `json:"displayName,omitempty"`
}

// Name: UpdateTrackFilterBody
type UpdateTrackFilterBody struct {
	// Name: UpdateTrackFilterBody.name
	Name *string `json:"name,omitempty"`
	// Name: UpdateTrackFilterBody.filter
	Filter *string `json:"filter,omitempty"`
}

